# Generated by Django 3.0.5 on 2022-01-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_created',
            new_name='date',
        ),
    ]
