# Generated by Django 3.0.5 on 2022-01-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20220108_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date',
            new_name='date_created',
        ),
    ]
